### ISSUE TITLE
Clean up invite users section

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/ctibutler_web_be#26]
![image](https://github.com/user-attachments/assets/0fd87adb-d1a1-4923-b51d-a4f53c348f44)

1. clean up remove button
  * button should be red
  * if only one row, do not show remove button
2. show button as greyed out until valid email entered
3. if team has no remaining invite, remove email entry and show "You have no remaining seats in your team, please upgrade your subscription to add more seats."

**Comment by olarid7852** [comment]
The number 2 is going to be a heavy operation, should I continue with it?

**Comment by himynamesdave** [comment]
@olarid7852 isn't is just a lookup of stripe reported team members - current team member = seats remaining. If 0, show message

Or there is more to it?

**Comment by olarid7852** [comment]
It should be number 2, actually

**Comment by himynamesdave** [comment]
@olarid7852 

![Image](https://github.com/user-attachments/assets/c49058b1-15e3-428f-916e-f76f5ac519cd)

button is always greyed out. impossible to add a user
